### ISSUE TITLE
Register to be notified of opportunities

### ISSUE THREAD

**Issue by RachelMuston** [canada-ca/devex#67]
Hey @markwooff, the link on the main page to 'Register to be notified of future opportunities' doesn't seem to be working.  When I click on it, nothing happens.  Here is the link:

https://beta.gcdevexchange.org/authentication/government

**Comment by RachelMuston** [comment]
The link from the french version of the main page works.  It is linking to:
https://gcdevexchange-carrefourproggc.org/fr/authentication/government 

So looks like the english page link is just missing the /en/

**Comment by markwooff** [comment]
I've fixed the link, however will need to fix the underlying language pickup issue. By default, the application should bring them to an English page.

**Comment by RachelMuston** [comment]
I'm still seeing the same link from the main page: https://beta.gcdevexchange.org/authentication/government

Should be https://beta.gcdevexchange.org/en/authentication/government  no?

**Comment by markwooff** [comment]
Links should now be fixed on prod :)
